export const GOOGLE_ADS_ID =
  process.env.NEXT_PUBLIC_GOOGLE_ADS_ID || "AW-18217037623";

export const CONTACT_FORM_CONVERSION_LABEL =
  process.env.NEXT_PUBLIC_GOOGLE_ADS_CONTACT_FORM_CONVERSION_LABEL || "";

export const CONTACT_FORM_CONVERSION_SEND_TO = CONTACT_FORM_CONVERSION_LABEL
  ? `${GOOGLE_ADS_ID}/${CONTACT_FORM_CONVERSION_LABEL}`
  : "";
